/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as FormIdIndexImport } from './routes/form/$id/index';

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')();
const FormIdPreviewLazyImport = createFileRoute(
  '/form/$id/preview'
)();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/index.lazy').then(d => d.Route)
);

const FormIdIndexRoute = FormIdIndexImport.update({
  path: '/form/$id/',
  getParentRoute: () => rootRoute,
} as any);

const FormIdPreviewLazyRoute = FormIdPreviewLazyImport.update({
  path: '/form/$id/preview',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/form/$id/preview.lazy').then(d => d.Route)
);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/form/$id/preview': {
      preLoaderRoute: typeof FormIdPreviewLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/form/$id/': {
      preLoaderRoute: typeof FormIdIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  FormIdPreviewLazyRoute,
  FormIdIndexRoute,
]);

/* prettier-ignore-end */
